=== tamas-pa/EGFIE3xmlGyak/EGFIE3_0924/iskola.dtd
<!DOCTYPE iskola
[
        <!ELEMENT iskola (tanar, tanar1, tantargy)>
        <!ELEMENT tanar (nev, szak)>
        <!ATTLIST tanar kod ID #REQUIRED>
        <!ELEMENT nev (#PCDATA)>
        <!ELEMENT szak (#PCDATA)>
        <!ELEMENT tantargy (tnev, osztaly)>
        <!ATTLIST tantargy kod ID #REQUIRED>
        <!ATTLIST tantargy oktato IDREF>
        <!ELEMENT trgynev (#PCDATA)>
        <!ELEMENT osztaly (#PCDATA)>
]>

=== tamas-pa/EGFIE3xmlGyak/EGFIE3_0924/iskola.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE iskola SYSTEM "iskola.dtd">
<iskola>
    <tanar kod="1">
        <nev>Iránytű Imre</nev>
        <szak>É szak</szak>
    </tanar>
    <tanar kod="2">
        <nev>Gusztáv Góliát</nev>
        <szag>Erő szak</szag>
    </tanar>
    <tantargy kod="1" oktato="2">
        <tnev>Nevezetes mítoszok</tnev>
        <osztaly>GG/1</osztaly>
    </tantargy>
</iskola>
